name: Convert and Update Markdown

on:
  push:
    branches: [ main ]

jobs:
  convert-and-update:
    runs-on: ubuntu-latest
    steps:
      # Checkout main branch (source files)
      - uses: actions/checkout@v4
        with:
          ref: main

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install jupyter jupytext nbconvert

      # Convert files to markdown
      - name: Convert to Markdown
        run: |
          # Convert notebooks
          find . -name '*.ipynb' -exec jupyter nbconvert --to markdown --no-execute {} \;
          
          # Convert Python files
          find . -name '*.py' ! -name 'config.json' -exec bash -c '
            echo "\`\`\`python" > "{}.md"
            cat "{}" >> "{}.md"
            echo "\`\`\`" >> "{}.md"
          ' \;

      # Checkout markdown branch and update files
      - name: Update markdown branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Checkout markdown branch
          git fetch origin markdown || true
          if git show-ref --verify --quiet refs/remotes/origin/markdown; then
            git checkout markdown
            git pull origin markdown
          else
            git checkout --orphan markdown
            git rm -rf --quiet .  # Only runs for new branch
          fi
          
          # Copy only markdown files and config.json
          find ../main -name '*.md' -exec cp --parents {} . \;
          cp ../main/config.json .
          
          # Commit changes
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update markdown files [auto]"
            git push origin markdown
          fi