name: Convert and Push to Docs Repo

on:
  push:
    branches: [ "main" ]

jobs:
  convert-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout source repo
      - name: Checkout code-examples
        uses: actions/checkout@v4

      # Set up Python + dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install jupyter jupytext nbconvert

      # Convert .ipynb to .ipynb.md (keeping original extension)
      - name: Convert notebooks to Markdown
        run: |
          find . -name '*.ipynb' -exec jupytext --to md --opt comment_magics=true {} \;

      # Convert .py to .md (regular markdown)
      - name: Convert Python scripts to Markdown
        run: |
          find . -name '*.py' ! -name '*test*.py' -exec bash -c '
            echo "\`\`\`python" > "{}.md"
            cat "{}" >> "{}.md"
            echo "\`\`\`" >> "{}.md"
          ' \;

      # Prepare files for target directory
      - name: Prepare docs/code_examples
        run: |
          mkdir -p docs/code_examples
          # Copy all markdown files (both .ipynb.md and .md) plus _category_.json
          find . \( -name '*.ipynb.md' -o -name '*.md' -o -name '_category_.json' \) ! -name 'README.md' -exec bash -c '
            target_path="docs/code_examples/${1#./}"
            mkdir -p "$(dirname "$target_path")"
            cp "$1" "$target_path"
          ' _ {} \;

      # Push changes
      - name: Push to brett-van-tussler.github.io
        run: |
          cd docs/code_examples
          git init
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add origin https://${{ secrets.BRETTVANTUSSLER_GITHUB_IO_DESTINATION }}@github.com/brett-van-tussler/brett-van-tussler.github.io.git
          git checkout -b main
          git add .
          git commit -m "Auto-update code examples from code-examples repo"
          git push origin main --force