name: Convert and Update Markdown

on:
  push:
    branches: [ main ]

jobs:
  convert-and-update:
    runs-on: ubuntu-latest
    steps:
      # Checkout main branch with full history
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for branch operations

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install jupyter jupytext nbconvert

      # Convert files to markdown
      - name: Convert to Markdown
        run: |
          # Convert notebooks
          find . -name '*.ipynb' -exec jupyter nbconvert --to markdown --no-execute {} \;
          
          # Convert Python files
          find . -name '*.py' ! -name 'config.json' -exec bash -c '
            echo "\`\`\`python" > "{}.md"
            cat "{}" >> "{}.md"
            echo "\`\`\`" >> "{}.md"
          ' \;

      # Update markdown branch incrementally
      - name: Update markdown branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create markdown branch if it doesn't exist
          if ! git show-ref --quiet refs/remotes/origin/markdown; then
            git checkout --orphan markdown
            git commit --allow-empty -m "Initial empty commit"
            git push origin markdown
            git checkout main
          fi
          
          # Switch to markdown branch
          git checkout markdown
          
          # Get the converted files from main branch
          git checkout main -- *.md *.ipynb.md config.json
          
          # Commit and push only if there are changes
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Update markdown files [auto]"
            git push origin markdown
          else
            echo "No changes to commit"
          fi
          
          # Return to main branch
          git checkout main